{% set name = "HiGHS" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ERGO-Code/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5ff96c14ae19592d3568e9ae107624cbaf3409d328fb1a586359f0adf9b34bf7

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make  # [unix]
    - {{ stdlib("c") }}

test:
  commands:
    - test -f ${PREFIX}/include/highs/Highs.h  # [unix]
    - test -f ${PREFIX}/lib/libhighs.so  # [linux]
    - if not exist %LIBRARY_PREFIX%\include\highs\Highs.h (exit 1)  # [win]

about:
  home: https://github.com/ERGO-Code/HiGHS
  summary: HiGHS is a high performance serial and parallel solver for large scale sparse linear optimization problems
  description: |
    HiGHS is a high performance serial and parallel solver for large scale sparse linear optimization problems
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://highs.dev
  dev_url: https://github.com/ERGO-Code/HiGHS

extra:
  recipe-maintainers:
    - julian-belina
    - DerThorsten
