{% set name = "HiGHS" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ERGO-Code/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a0d09371fadb56489497996b28433be1ef91a705e3811fcb1f50a107c7d427d1

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - ninja  # [win]
    - make  # [not win]
    - {{ stdlib("c") }}

test:
  source_files:
    - check/instances/afiro.mps
  commands:
    - test -f ${PREFIX}/include/highs/Highs.h  # [unix]
    - test -f ${PREFIX}/lib/libhighs.so  # [linux]
    - if not exist %LIBRARY_PREFIX%\include\highs\Highs.h (exit 1)  # [win]
    - highs check/instances/afiro.mps

about:
  home: https://github.com/ERGO-Code/HiGHS
  summary: HiGHS is a high performance serial and parallel solver for large scale sparse linear optimization problems
  description: |
    HiGHS is a high performance serial and parallel solver for large scale sparse linear optimization problems
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://highs.dev
  dev_url: https://github.com/ERGO-Code/HiGHS

extra:
  recipe-maintainers:
    - julian-belina
    - DerThorsten
